version: "3.8"
services:
  postgresdb:
    image: postgres
    container_name: postgres_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sri.cloudengineer@gmx.com
      PGADMIN_DEFAULT_PASSWORD: sri@pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresdb
volumes:
  postgres-data:
  pgadmin-data:


